package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import java.util.Optional;
import java.util.function.Supplier;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;

import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;

import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;

import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    /** Swerve request to apply during robot-centric path following */
    private final SwerveRequest.ApplyRobotSpeeds m_pathApplyRobotSpeeds = new SwerveRequest.ApplyRobotSpeeds();


    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();

    /* SysId routine for characterizing translation. This is used to find PID gains for the drive motors. */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> {
                // Apply the voltage to all modules
                setControl(m_translationCharacterization.withVolts(output));
                
                // First pass: collect all data and calculate mean
                double[] voltages = new double[4];
                double[] velocities = new double[4];
                double[] positions = new double[4];
                
                double totalVelocity = 0;
                
                for (int i = 0; i < 4; i++) {
                    var module = getModule(i);
                    voltages[i] = module.getDriveMotor().getMotorVoltage().getValueAsDouble();
                    velocities[i] = module.getDriveMotor().getVelocity().getValueAsDouble();
                    positions[i] = module.getDriveMotor().getPosition().getValueAsDouble();
                    
                    totalVelocity += velocities[i];
                }
                
                // Calculate mean velocity
                double meanVelocity = totalVelocity / 4;
                
                // Calculate standard deviation for velocity (to detect outliers)
                double variance = 0;
                for (int i = 0; i < 4; i++) {
                    double dev = velocities[i] - meanVelocity;
                    variance += dev * dev;
                }
                double stdDev = Math.sqrt(variance / 4);
                
                // Second pass: average only modules within 1 standard deviation of the mean
                double sumVoltage = 0;
                double sumVelocity = 0;
                double sumPosition = 0;
                int validModules = 0;
                
                for (int i = 0; i < 4; i++) {
                    // Include module if its velocity is within 1 standard deviation of the mean
                    if (Math.abs(velocities[i] - meanVelocity) <= stdDev) {
                        sumVoltage += voltages[i];
                        sumVelocity += velocities[i];
                        sumPosition += positions[i];
                        validModules++;
                    }
                }
                
                // Calculate robust averages (if all modules are outliers, fall back to regular mean)
                double avgVoltage = validModules > 0 ? sumVoltage / validModules : (voltages[0] + voltages[1] + voltages[2] + voltages[3]) / 4;
                double avgVelocity = validModules > 0 ? sumVelocity / validModules : meanVelocity;
                double avgPosition = validModules > 0 ? sumPosition / validModules : (positions[0] + positions[1] + positions[2] + positions[3]) / 4;
                
                // Log the robust averages - these are what SysId will use
                SignalLogger.writeDouble("voltage", avgVoltage);
                SignalLogger.writeDouble("velocity", avgVelocity);
                SignalLogger.writeDouble("position", avgPosition);
                
                // Also log which modules were included in the average (useful for debugging)
                SignalLogger.writeDouble("valid_modules_count", validModules);
                
                // Optional: still log individual modules for debugging
                for (int i = 0; i < 4; i++) {
                    String moduleName = "drive_" + i;
                    SignalLogger.writeDouble(moduleName + "_voltage", voltages[i]);
                    SignalLogger.writeDouble(moduleName + "_velocity", velocities[i]);
                    SignalLogger.writeDouble(moduleName + "_position", positions[i]);
                }
                
                // Optional: also log the commanded voltage for reference
                SignalLogger.writeDouble("commanded_voltage", output.in(Volts));
            },
            null,
            this
        )
    );

    /* SysId routine for characterizing steer. This is used to find PID gains for the steer motors. */
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(7), // Use dynamic voltage of 7 V
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdSteer_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            volts -> {
                // Apply the voltage to steer motors
                setControl(m_steerCharacterization.withVolts(volts));
                
                // First pass: collect all data and calculate mean angular velocity
                double[] voltages = new double[4];
                double[] angularVelocities = new double[4];
                double[] angularPositions = new double[4];
                
                double totalAngularVelocity = 0;
                
                for (int i = 0; i < 4; i++) {
                    var module = getModule(i);
                    // For steer motors, we want angular measurements
                    voltages[i] = module.getSteerMotor().getMotorVoltage().getValueAsDouble();
                    angularVelocities[i] = module.getSteerMotor().getVelocity().getValueAsDouble(); // This is angular velocity
                    angularPositions[i] = module.getSteerMotor().getPosition().getValueAsDouble(); // This is angular position
                    
                    totalAngularVelocity += angularVelocities[i];
                }
                
                // Calculate mean angular velocity
                double meanAngularVelocity = totalAngularVelocity / 4;
                
                // Calculate standard deviation for angular velocity (to detect outliers)
                double variance = 0;
                for (int i = 0; i < 4; i++) {
                    double dev = angularVelocities[i] - meanAngularVelocity;
                    variance += dev * dev;
                }
                double stdDev = Math.sqrt(variance / 4);
                
                // Second pass: average only modules within 1 standard deviation of the mean
                double sumVoltage = 0;
                double sumAngularVelocity = 0;
                double sumAngularPosition = 0;
                int validModules = 0;
                
                for (int i = 0; i < 4; i++) {
                    // Include module if its angular velocity is within 1 standard deviation of the mean
                    if (Math.abs(angularVelocities[i] - meanAngularVelocity) <= stdDev) {
                        sumVoltage += voltages[i];
                        sumAngularVelocity += angularVelocities[i];
                        sumAngularPosition += angularPositions[i];
                        validModules++;
                    }
                }
                
                // Calculate robust averages (if all modules are outliers, fall back to regular mean)
                double avgVoltage = validModules > 0 ? sumVoltage / validModules : 
                    (voltages[0] + voltages[1] + voltages[2] + voltages[3]) / 4;
                double avgAngularVelocity = validModules > 0 ? sumAngularVelocity / validModules : meanAngularVelocity;
                double avgAngularPosition = validModules > 0 ? sumAngularPosition / validModules : 
                    (angularPositions[0] + angularPositions[1] + angularPositions[2] + angularPositions[3]) / 4;
                
                // Log the robust averages - these are what SysId will use for steer analysis
                SignalLogger.writeDouble("steer_voltage", avgVoltage);
                SignalLogger.writeDouble("steer_velocity", avgAngularVelocity); // Angular velocity in rotations per second
                SignalLogger.writeDouble("steer_position", avgAngularPosition); // Angular position in rotations
                
                // Also log which modules were included in the average (useful for debugging)
                SignalLogger.writeDouble("steer_valid_modules_count", validModules);
                
                // Optional: still log individual modules for debugging
                for (int i = 0; i < 4; i++) {
                    String moduleName = "steer_" + i;
                    SignalLogger.writeDouble(moduleName + "_voltage", voltages[i]);
                    SignalLogger.writeDouble(moduleName + "_angular_velocity", angularVelocities[i]);
                    SignalLogger.writeDouble(moduleName + "_angular_position", angularPositions[i]);
                }
                
                // Optional: also log the commanded voltage for reference
                SignalLogger.writeDouble("steer_commanded_voltage", volts.in(Volts));
            },
            null,
            this
        )
    );

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on importing the log to SysId.
     */
    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
        new SysIdRoutine.Config(
            /* This is in radians per second², but SysId only supports "volts per second" */
            Volts.of(Math.PI / 6).per(Second),
            /* This is in radians per second, but SysId only supports "volts" */
            Volts.of(Math.PI),
            null, // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdRotation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> {
                /* output is actually radians per second, but SysId only supports "volts" */
                setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                /* also log the requested output for SysId */
                SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
            },
            null,
            this
        )
    );

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineSteer;

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
     * @param modules               Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }

        configureAutoBuilder();
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }

        configureAutoBuilder();

    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        Matrix<N3, N1> odometryStandardDeviation,
        Matrix<N3, N1> visionStandardDeviation,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }

        configureAutoBuilder();

    }

     private void configureAutoBuilder() {
        try {
            var config = RobotConfig.fromGUISettings();
            AutoBuilder.configure(
                () -> getState().Pose,   // Supplier of current robot pose
                this::resetPose,         // Consumer for seeding pose against auto
                () -> getState().Speeds, // Supplier of current robot speeds
                // Consumer of ChassisSpeeds and feedforwards to drive the robot
                (speeds, feedforwards) -> setControl(
                    m_pathApplyRobotSpeeds.withSpeeds(ChassisSpeeds.discretize(speeds, 0.020))
                        .withWheelForceFeedforwardsX(feedforwards.robotRelativeForcesXNewtons())
                        .withWheelForceFeedforwardsY(feedforwards.robotRelativeForcesYNewtons())
                ),
                new PPHolonomicDriveController(
                    // PID constants for translation
                    new PIDConstants(10, 0, 0),
                    // PID constants for rotation
                    new PIDConstants(7, 0, 0)
                ),
                config,
                // Assume the path needs to be flipped for Red vs Blue, this is normally the case
                () -> DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red,
                this // Subsystem for requirements
            );
        } catch (Exception ex) {
            DriverStation.reportError("Failed to load PathPlanner config and configure AutoBuilder", ex.getStackTrace());
        }
    }

    /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }

    @Override
    public void periodic() {
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is disabled.
         * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation
                );
                m_hasAppliedOperatorPerspective = true;
            });
        }

    }

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement
     *     in the form [x, y, theta]ᵀ, with units in meters and radians.
     */
    @Override
    public void addVisionMeasurement(
        Pose2d visionRobotPoseMeters,
        double timestampSeconds,
        Matrix<N3, N1> visionMeasurementStdDevs
    ) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }

    public Pose2d getPose(){
        return this.getState().Pose;
    }
}
